version: "3.9"
services:
    web:
        build:
            args:
                ConnectionString: "Server=db;Database=master;User=sa;Password=${DatabasePassword};"        
            context: .      
        ports:
            - "80:6003"
            - "443:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw
        environment:
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
        depends_on:
            - db            
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "1433:1433" 
            - "1434:1434" 
            - "1431:1431"
        volumes:
            - ./mssql/data:/var/opt/mssql/data:rw
            - ./mssql/logs:/var/opt/mssql/log:rw
        environment:
            SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: "Y"
