FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
ARG ConnectionString=default_connection_string
ENV ConnectionString=$ConnectionString
WORKDIR /app
COPY . .
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
RUN chmod +x ./entrypoint_dbScaffold.sh
FROM build AS publish
RUN ["dotnet", "publish", "my-demo-app.csproj", "-c", "Release", "-o", "/app" ]
FROM publish AS final
WORKDIR /app
COPY --from=publish /app/entrypoint_dbScaffold.sh .
COPY --from=publish /app .
ENTRYPOINT ./entrypoint_dbScaffold.sh $ConnectionString