FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
ARG ConnectionString=default_connection_string
ENV ConnectionString=$ConnectionString
WORKDIR /app
COPY my-demo-app.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build my-demo-app.csproj -c Release -o /app/build
RUN chmod +x ./entrypoint_dbmigrate.sh

FROM build AS publish
RUN dotnet publish my-demo-app.csproj -c Release -o /app
FROM publish AS final
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:6003;https://+:6004
EXPOSE 6003 6004
WORKDIR /app

COPY --from=publish /app/entrypoint_dbmigrate.sh .
COPY --from=publish /app .
COPY --from=publish /app/etc/ssl/openssl.cnf /etc/ssl/openssl.cnf

ENTRYPOINT ./entrypoint_dbmigrate.sh ${ConnectionString}
