version: "3.9"
services:
    web:
        build:
            args:
                ConnectionString: "${DatabaseConnectionString};"
            context: .
            dockerfile: Dockerfile_DbScaffold
        container_name: "scaffold"             
        volumes:
            - ./Data/Generated:/app/DbModels:rw       
        depends_on:
            - db             
    db:
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        user: root        
        container_name: "database"
        restart: always      
        ports:
            - "1433:1433"       
        volumes:
            - ./data/mssql/data/:/var/opt/mssql/data
        environment:
            MSSQL_SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: 1
            MSSQL_PID: Developer