FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG ConnectionString=default_connection_string
ENV ConnectionString=$ConnectionString
WORKDIR /app
COPY my-demo-app.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build my-demo-app.csproj -c Release -o /app/build
RUN chmod +x ./entrypoint_dbscaffold.sh

FROM build AS publish
RUN dotnet publish my-demo-app.csproj -c Release -o /app
FROM publish AS final
WORKDIR /app
COPY --from=publish /app/entrypoint_dbscaffold.sh .
COPY --from=publish /app .
ENTRYPOINT bash ./entrypoint_dbscaffold.sh $ConnectionString